version: "3.9"

services:
  mysqldb1:
    image: mysql:8.0
    container_name: mysqldb1
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./database/db1:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    ports:
      - "8833:3306"
    networks:
      - tmklan

  admindb1:
    image: phpmyadmin:latest
    container_name: admindb1
    restart: always
    links:
      - mysqldb1
    env_file: .env
    environment:
      - PMA_HOST=mysqldb1
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - PMA_PORT=3306
      - PMA_ARBITRARY=1
    ports:
      - "8080:80"
    networks:
      - tmklan

networks:
  tmklan:
    driver: bridge
